### PR TITLE
elrs-add-br3

### PR DESCRIPTION
**Pull request by jlpoltrack**
Title, plus cleaned up the table a little.

### CODE REVIEW

**Comment by olliw42** [comment]
lgtm

but it's confusing. It first is claimed to tell te supported receivers, but the selected cannot be found ...

**Comment by olliw42** [comment]
D PA probably also needed

**Comment by olliw42** [comment]
well, the first chapter claims "these are supported", makes me look at this chapter and look into the json. even though not needed at all for the selected devices ...

I would think the logic would be rather: These are the selected de  ices which are supported, and in addition these are also supported ...

bottom line: we need to get a good plan how to hanlde the various devices/ases, as discussed in another PR ...

so, I'm happy for this to be merged for sure, but the situation is confusing IMHO

**Comment by jlpoltrack** [comment]
Gotcha - will track here: https://github.com/olliw42/mLRS-docu/issues/153

**Pull request merged**
