### PR TITLE
PARAMETERS: excluded frequencies, Rx Out RSSI & LQ Ch setting

### PR DESCRIPTION
**Pull request by olliw42**
- mention excluded frequencies for 2.4 GHz
- correct Rx Out RSSI Ch setting
- add Rx Out LQ Ch setting
- some tidy

### CODE REVIEW

**Comment by jlpoltrack** [comment]
Looks good to me.  Just one thought - does it make sense to recommend Channels 13-16 for LQ and RSSI as otherwise they would only be 3 value RC channels?

**Comment by olliw42** [comment]
I don't know and don't actually have an opinion ... from what whsqz said it looked to me that "everyone" kind of would use 15 & 16 anyways ... I really don't know what users would want to hear here :)

**Comment by jlpoltrack** [comment]
Fair enough, merging.

**Comment by olliw42** [comment]
THX!

**Pull request merged**
