### PR TITLE
E77 easy solder, SWD may need RESET

### PR DESCRIPTION
**Pull request by olliw42**
title says it :)

### CODE REVIEW

**Comment by jlpoltrack** [comment]
Minor note - ST-Link docs refer to this pin as 'NRST' so maybe we say 'NRST / RESET' instead of just 'RESET'

image

**Comment by olliw42** [comment]
good call, made changes

**Comment by jlpoltrack** [comment]
Looks good, merging.

**Comment by olliw42** [comment]
THX !

**Pull request merged**
