### PR TITLE
Link stats page

### PR DESCRIPTION
**Pull request by jlpoltrack**
First pass at a link stats page and small cleanup of CRSF sensors page.

### CODE REVIEW

**Comment by olliw42** [comment]
fantastic

I think you could separate out the changes on the CRSF sensor page, as these won't need discussion but just correct for the current state of affairs, i.e., could go in immediately

**Comment by jlpoltrack** [comment]
> I think you could separate out the changes on the CRSF sensor page, as these won't need discussion but just correct for the current state of affairs, i.e., could go in immediately

Sure :) https://github.com/olliw42/mLRS-docu/pull/55

**Comment by olliw42** [comment]
THX!
concerning the link statistics, the situation is a bit more involved.
1. there are four metrics: 
    - LQ
    - RSSI
    - SNR
    - byte rate
2. there are not only two but three LQ vaules, since the uplink (tx->rx) is characterized by two LQ values
    - uplink (tx->rx) LQ for the "higher reliable" rc data, let's call it rxLQ
    - uplink (tx->rx) LQ for serial data and the remaining rx data, let's call it rxLQser (generally rxLQser <= rxLQ)
    - downlink (rx->tx) LQ (which is then only for serial data since there is no rc data), let's call it txLQ
 3. for each unit with diversity systems we also do have two RSSI & SNR

Accordingly, it's a bit more complicated as regards to which values is reported in which field under which condition ...

**Comment by jlpoltrack** [comment]
Thanks for the feedback, I tried to focus on what is available to the user when flying, e.g. either in ArduPilot or on the radio - perhaps a note explaining that would make sense?  I can certainly add in byte rate as that would be available within the 'stats' panel in Mission Planner.

More stats are certainly available but if I understand correctly they only way to expose them would be using debug?

- Is rxLQser available outside of debug?
- Are any diversity pieces available outside of debug?

**Comment by olliw42** [comment]
>  I tried to focus on what is available to the user when flying

yes
I think it might be usefull however to sketch the fuller scheme, to better understand what each available piece means (at least my brain would work that way LOL)

> More stats are certainly available but if I understand correctly they only way to expose them would be using debug?

they are all available (and more) when using mbridge.

IMG_20220319_130426

I do have in mind to do at some point in time a lua which also would expose these info in the CRSF case. I.e., make some additions to the CRSF protocol so these data can be retrieved too.

From a general view, while I'm slightly "pissed off" at the reception it got, I still would hoppe that we as a community could excert enough pressure on ArduPilot to  make them considering adding a new mavlink message. I have made a respective PR in the mavlink repo and there is also a branch in my ardupilot fork which uses that. (https://github.com/mavlink/mavlink/pull/1920) (note that DroneCan appears to be very close to include a similar CAN message ... which is quite hillarious, that DroneCAN will have that and MAVLink not, but shows the money trail at work in ArduPilot).

So, while you are correct, I somehow carry a hope with me that this may change.

**Comment by jlpoltrack** [comment]
I'll expand this to be more inclusive and to show what is possible as opposed to just what is available today,

> they are all available (and more) when using mbridge.

For my own knowledge, isn't mBridge exposing what is available in the frameStatus struct: https://github.com/olliw42/mLRS/blob/main/mLRS/Common/frame_types.h#L56-L69 (and the Tx is providing the Bps metrics)?  If so, wouldn't this mean that pieces like snr1/2 on the Rx side wouldn't be able to displayed (and would require debug?).

**Comment by olliw42** [comment]
SH.T I again wrote into your meassage modifying it ... this dammed github shoudl just not allow this ... SORRY

**Comment by olliw42** [comment]
the active antenna are the a1 a2 things in the pic
think in terms of available data on the tx, crsf only provides some of them, mbridge provides them all, so crsf is a subset of mbridge
the tx a's are currently always just a1 since as emntioned mlrs doesn't yet do antenna transmit diversity

**Comment by jlpoltrack** [comment]
- Added data rate and antenna sections.
- Started a table showing where each link stat can be found - any feedback on this approach would be good.

**Comment by jlpoltrack** [comment]
Stale, so closing.  Can revisit if needed.

**Pull request closed without merging**
