### PR TITLE
Explain Buzzer option LP better

### PR DESCRIPTION
**Pull request by rotorman**

### CODE REVIEW

**Comment by olliw42** [comment]
many thx.
Maybe I can nitpick again. The "structure" of the descriptions is a bit along that in the first paragraph only the "facts" are mentioned, and that explanations of what what setting does comes in a separate parapgraph. Maybe you could change such that your addition is in the next paragraph.  Maybe one could even extend it, like 

Enables the buzzer, and selects what data it reflects. Can be "off", "LP", "rxLQ".

LP stands for Lost Packet, and here the buzzer emits a short beep for any lost packet. rxLQ stands for receiver Link Quality, and here the buzzer beeps every second, with the beep length reflecting LQ (longer beep = lower LQ).

and dito for Rx Buzzer. Suggested language is rough of course

**Comment by olliw42** [comment]
I'm actually not sure if the rxLQ option is useful at all, and could/should actually be removed ...

**Comment by rotorman** [comment]
I changed the text according to your suggestions and keeping rxLQ in, as fw presently supports it.

**Comment by olliw42** [comment]
LGTM

@jlpoltrack ?

**Comment by jlpoltrack** [comment]
Looks good, merging.  Thanks!

**Pull request merged**
