### PR TITLE
Update ARDUPILOT.md

### PR DESCRIPTION
**Pull request by 4O6FPV**
corrected a link that was wrong.

### CODE REVIEW

**Review by jlpoltrack — COMMENTED** [review]
Period not needed after the URL.

**Review by 4O6FPV — COMMENTED** [review]
I think I did this right still learning this system

**Comment by jlpoltrack** [comment]
Looks good, merging.  Many thanks for the catch.

**Comment by olliw42** [comment]
@4O6FPV MANY thx from my side too!

**Pull request merged**
