### PR TITLE
Swap links of M4OTX and SiK setup pages

### PR DESCRIPTION
**Pull request by olliw42**
I have that in mind since a longer while, to better reflect potential importance
let's see what you say :)

### CODE REVIEW

**Comment by jlpoltrack** [comment]
New order works for me.

I wonder if we should also standardize on the language - e.g. 'Setup for SBus Radios' instead of 'Basic setup...' or maybe just remove 'Setup for', e.g.:

- CRSF...
- Sik Replacement
- SBus Radios
- MAVLink for OpenTx

**Comment by olliw42** [comment]
> I wonder if we should also standardize on the language

good idea. Made an attempt.

**Comment by jlpoltrack** [comment]
Looks good. Minor note, the 'Configuration for ArduPilot Systems' line is now the only one with white text on the entire page:

image

Perhaps just making the entire text a link?

**Comment by olliw42** [comment]
good point. Done.
:)

**Comment by jlpoltrack** [comment]
Looks good - merging.

**Comment by olliw42** [comment]
THX

**Pull request merged**
