### PR TITLE
E77-MBL, WioE5, R9 boards: add info on frequency range and output power

### PR DESCRIPTION
**Pull request by olliw42**
adds info on supported RF band and max RF output power to three boards/systems.

might be useful info.

### CODE REVIEW

**Comment by olliw42** [comment]
grrrr ... how can one get the two lines into two lines without this damed big space between the lines ...

**Comment by jlpoltrack** [comment]
Good idea.  I don't believe the '\<br>' has any effect, perhaps it would make sense to have these as bullets using '-' ?  Here's what I see in the preview for the branch:

image

**Comment by olliw42** [comment]
the <br> is in fact doing the narrow line break :) (https://github.com/mattcone/markdown-guide/blob/master/_basic-syntax/line-breaks.md)
I tried bullets (and also table) but they looked not as I wanted
the preview shows the same I do see, and shows what I wanted to do

this does NOT mean that how it looks is a good idea.
Pl try and suggests otherwise.

I actually initally wanted a table, without a header, but it seems the markup doesn't allow this (one could do html, if I understood it correctly, but ...)

**Comment by olliw42** [comment]
cool !!
I do like this :)
if you also like this it would be great if you could do that for all

I was a bit unsure about the language "(depending on module)". Not sure everyone will understand.

**Comment by jlpoltrack** [comment]
> I was a bit unsure about the language "(depending on module)". Not sure everyone will understand.

I put the hardware in parentheses to hopefully make it clear.

One other note - did see that Frsky page says 'depending on the module' - I did some searching and I don't see different hardware versions although I vaguely recall Frsky labeled the hardware different for EU region but this was just different firmware...

**Comment by olliw42** [comment]
frsky, good question.
when I bought my stuff I think I was watching out for 868 over 915. It could be that it are just the antenna which are different ...
I guess you are right and that comment is indeed incorrect

**Comment by olliw42** [comment]
I would wish I would know also teh weight of teh WioE5 mini module ... I only have one and it has quite some stuff soldered to it ... LOL

**Comment by jlpoltrack** [comment]
@4O6FPV 
Any chance you could weigh (in grams) a bare E5 mini and / or bare E5 grove?

**Comment by olliw42** [comment]
ah, good idea to ask him :)

**Comment by olliw42** [comment]
minique got a rough measure of ca 8 grams per unit, https://discord.com/channels/1005096100572700794/1005096101239603232/1125813490377035877
let's see what other measurements we may get

**Comment by olliw42** [comment]
LGTM
:)

**Pull request merged**
