### PR TITLE
Lua bw addition

### PR DESCRIPTION
**Pull request by jlpoltrack**
Couple pieces added to specify which version of the lua should be used.

### CODE REVIEW

**Comment by olliw42** [comment]
nice
why lua and not Lua? It's a name like CRSF, isn't it, and Lua calls itself "Lua"...

**Comment by jlpoltrack** [comment]
> nice why lua and not Lua? It's a name like CRSF, isn't it, and Lua calls itself "Lua"...

You're right, updated.

**Comment by olliw42** [comment]
LGTM

I wonder if one shouldn't leave a comment about that the bw version is somewhat limited

**Comment by jlpoltrack** [comment]
> I wonder if one shouldn't leave a comment about that the bw version is somewhat limited

Added

**Comment by olliw42** [comment]
I can't find anything to complain anymore LOL
LGTM

**Comment by jlpoltrack** [comment]
> I can't find anything to complain anymore LOL LGTM

Sounds good, note that I removed the '128x64' for black and white screen radios as it looks like this works on radios like the Frsky Taranis with 212x64 resolution as well https://www.rcgroups.com/forums/showpost.php?p=51180873&postcount=1821

**Comment by olliw42** [comment]
excellent
LGTM

**Pull request merged**
