### PR TITLE
matek docu

### PR DESCRIPTION
**Pull request by olliw42**
title says it

just to make a 2st step

anyone welcome to work further on it :)

### CODE REVIEW

**Comment by olliw42** [comment]
matek devices are online on their web page now (not yet in shop)
https://www.mateksys.com/?page_id=12174

as a first start we probably simply can refer to their pages, their documentation is pretty good.

**Comment by jlpoltrack** [comment]
Does this approach make sense for the short term?

- On Matek Sys page, link to their individual product pages
- Add link to Matek Sys page from ReadMe
- Can include the individual products in a merge but just not link to them

**Comment by olliw42** [comment]
sounds very reasonable :)

**Comment by jlpoltrack** [comment]
> I think it would be good to just have something, so users are not confused it's not in our docs :)

Made an update to incorporate suggestions

**Comment by olliw42** [comment]
GREAT

can you take over? I'm going to leave for vaccation tomorrow and won't be able to do all this github stuff

**Comment by olliw42** [comment]
THX !!!!

**Pull request merged**
