### PR TITLE
lua version note

### PR DESCRIPTION
**Pull request by jlpoltrack**
One line note for EdgeTx.  To address https://github.com/olliw42/mLRS-docu/issues/113

### CODE REVIEW

**Comment by olliw42** [comment]
THX
do we know 2.8 does not work?

**Comment by jlpoltrack** [comment]
I could downgrade my radio to 2.8.0 to try - do we want to limit testing there?  Release of that version was November 2022.

**Comment by olliw42** [comment]
na, just was curious if the have info
claiming 2.9 is perfectly fine for me

LGTM

do we have info on OTX? I would think that OTX should be unproblematic, i.e. everyone will be on something which works, i.e. we don't need a comment here

**Comment by jlpoltrack** [comment]
> do we have info on OTX? I would think that OTX should be unproblematic, i.e. everyone will be on something which works, i.e. we don't need a comment here

I haven't run OpenTx in time that I've been using mLRS - so can't comment here.

**Comment by olliw42** [comment]
:)

as said, lgtm :)

**Pull request merged**
