### PR TITLE
Parameter update

### PR DESCRIPTION
**Pull request by jlpoltrack**
- Remove Tx Line End
- Remove Rx Buzzer
- Add Tx Power Sw
- Add Rx Power Sw

### CODE REVIEW

**Comment by olliw42** [comment]
lgtm

should we leave a comment that also more complex power settings via switch would be possible?

**Comment by jlpoltrack** [comment]
- Version updated to 1.3.04
- Additional line on the extra power levels

**Comment by olliw42** [comment]
any reason to hold back?

**Comment by jlpoltrack** [comment]
Well 1.3.04 doesn't exist :) otherwise it can be merged.

**Comment by olliw42** [comment]
haha ... that's true LOL

**Comment by jlpoltrack** [comment]
Now that 1.3.04 is out - good to merge?

**Comment by olliw42** [comment]
ABSOLUTELY 
thx for recalling

**Pull request merged**
