### PR TITLE
FRM303 power note, limitations

### PR DESCRIPTION
**Pull request by jlpoltrack**
Title

### CODE REVIEW

**Comment by jlpoltrack** [comment]
@olliw42 Could you kindly take a look at and provide any feedback?

**Comment by olliw42** [comment]
oh sorry
I think the top table was intended to give users a quick overview of some technical aspects, to see if the module might fit their purpose, and not as location for use advices

maybe a note, or maybe a separate chapter after rx and before OLED mod

**Comment by jlpoltrack** [comment]
All good, updates made:

- Power reco added to notes section of Tx, Rx
- Seperate chapter line for Limitations

**Comment by olliw42** [comment]
concentration :) subchapter of flashing?

I kind of liked it in the table, but chapter is sure good too :)

**Comment by jlpoltrack** [comment]
Should have a coffee first :).  Limitations moved back to the table.

**Comment by olliw42** [comment]
:)
lgtm

**Comment by olliw42** [comment]
MANY THX !!

**Pull request merged**
