### PR TITLE
r9 upload improvements

### PR DESCRIPTION
**Pull request by jlpoltrack**
Title, to incorporate suggestions from @4O6FPV

### CODE REVIEW

**Comment by olliw42** [comment]
lgtm

suggestion to keep attribution. Either fist merge the previous PR and then yours as follow up PR, or add as coauther (add a line `Co-authored-by: name <name@example.com>` into the final commit message, https://docs.github.com/de/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#commits-mit-co-autor-auf-github)

**Comment by jlpoltrack** [comment]
@4O6FPV If you want, happy to give you credit on this PR but would need your Github no reply email.  You can find it under Account > Settings > Emails, looks like 'ID+USERNAME@users.noreply.github.com'

**Comment by olliw42** [comment]
Co-authored-by: @4O6FPV

**Comment by jlpoltrack** [comment]
> this should do it IMHO

Okay, added a commit with co-author credit.

**Comment by 4O6FPV** [comment]
> @4O6FPV If you want, happy to give you credit on this PR but would need your Github no reply email. You can find it under Account > Settings > Emails, looks like '[ID+USERNAME@users.noreply.github.com](mailto:ID+USERNAME@users.noreply.github.com)'

@jlpoltrack 
No need just hope it clears up some confusion. Sorry for wasting  your guys time earlier. I am not well versed in github but trying to learn more.

**Pull request merged**
