### PR TITLE
Update MSPX.md

### PR DESCRIPTION
**Pull request by ltrzcinski**
- section title changed
- content enriched with tx/rx/inav configurator screens to improve user journey and make configuration process easier

### CODE REVIEW

**Comment by olliw42** [comment]
MANY THX! much appreciated

@jlpoltrack @b14ckyy

my first thought is that I think the Tx configuration should come much later down, since there is not anything one is necessarily required to do. I.e. the defaults will work just fine. Or at least it should say that one doesn't necessarily need to do anything.

I find it a bit confusing that the 115200 baud is highlighted by a red box ... I would interpret this to indicate it's something important, but it's not really (as much as I can see)

maybe one shoudl use a screen shot of latest dev version, as the CLiLineEnd parameter is gone.

**Comment by ltrzcinski** [comment]
@olliw42 @jlpoltrack @14ckyy 
As long as TX config is irrelevant here, feel free to remove this subsection. I just did not know whether setting TX in a different way may cause issues with config. From user perspective, this was my doubt when looking into documentation: can I set TX in whatever way? May particular parameter influence configuration? This can be removed but maybe it would be worth to put one sentence to address TX configuration. Up to you guys :)

**Comment by olliw42** [comment]
I guess if it created confusion there shoudl be a section, and if it's just ot say nothing to do ... 

the changes shoudl be such that YOU fell you would have gotten along better

**Comment by b14ckyy** [comment]
I think the Images with the red boxes make sense but maybe just make clear that these are not values that HAVE to be set that way but instead that these have an affect. 

@olliw42 Yes I agree for the receiver there is basically nothing to do. It also does not matter what baud rate is set there when using BLE with INAV configurator. That could be a 1-liner side note at the end. 

For the Receiver config I suggest to put that in after this block here: 
image

Instead of describing the Tx mLRS settings it makes more sense to show a screenshot of the sensor page and explain how to scan for sensors afterwards. This can also be a test to see if the connection is successful in both directions.

**Comment by ltrzcinski** [comment]
@b14ckyy : thanks, that's a good idea. I can add steps for sensors discovery. What we can consider is also to update inav LUA.md  I was receiving inav lua script infinite "Loading" error as shown on discord because I haven't rebooted radio after discovering new sensors. But as mentioned lua is separate topic. For config - we can just close the config workflow with last step of discovering new sensors and rebooting radio. Makes sense? Lemme know pls.

**Comment by b14ckyy** [comment]
sounds good to me. You can add a link to the INAV lua as an example then, so people will find that specific documentation easier.

**Comment by jlpoltrack** [comment]
@ltrzcinski  @b14ckyy Converted this to a draft PR - once you're happy with it, you can change to 'Ready for review' and I will take a look at that point :)

**Comment by olliw42** [comment]
@jlpoltrack 
I've looked at it and compared to current version, and it seems it doesn't contain anything which needs to be carried over. 
I think it can be cosed.

**Pull request closed without merging**
