### PR TITLE
WioE5, E77 MBL, R9, list supported modes

### PR DESCRIPTION
**Pull request by olliw42**
title says it

follow up on https://discord.com/channels/1005096100572700794/1005096101239603232/1126471820590194749

### CODE REVIEW

**Comment by jlpoltrack** [comment]
Quick notes:
- should the 'S' in 'supported Modes' be capitalized?
- related, should the 'm' in max. RF Output Power' be capitalized?

**Comment by olliw42** [comment]
good questions
I do not have an opinion however
pl decide :)

**Comment by jlpoltrack** [comment]
Let's have all caps since it is a table.  Let me know if any feedback otherwise will merge later today.

**Comment by olliw42** [comment]
great. MAny thx for the corrections.

LGTM

**Pull request merged**
